instrumentation:
    extensions:
        - .js
    excludes: ['public/**', 'docs/**', 'coverage/**', 'spec/**', 'dist/**', 'stylesheets/**', 'templates/**']
    include-all-sources: true
reporting:
    dir: ./docs/coverage
